apiVersion: v1
kind: Namespace
metadata:
  name: portainer-nodeport
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-nodeport-sa-clusteradmin
  namespace: portainer-nodeport
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-nodeport-crb-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: portainer-nodeport-sa-clusteradmin
  namespace: portainer-nodeport
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-nodeport
  namespace: portainer-nodeport
spec:
  type: NodePort
  selector:
    name: portainer-nodeport
  ports:
  - port: 9000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-nodeport
  namespace: portainer-nodeport
spec:
  selector:
    matchLabels:
      name: portainer-nodeport
  template:
    metadata:
      labels:
        name: portainer-nodeport
    spec:
      serviceAccountName: portainer-nodeport-sa-clusteradmin
      containers:
      - name: portainer-nodeport
        image: portainer/base
        # imagePullPolicy: "Never"
        command: ["/app/portainer"]
        args: ["--no-analytics",]
        ports:
        - containerPort: 9000
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app
          name: portainer-nodeport-dist
      volumes:
      - name: portainer-nodeport-dist
        hostPath:
          path: /home/baron_l/projects/pro/portainer/portainer/dist
          type: Directory
