apiVersion: v1
kind: Namespace
metadata:
  name: portainer-local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-local-sa-clusteradmin
  namespace: portainer-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-local-crb-clusteradmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: portainer-local-sa-clusteradmin
  namespace: portainer-local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-local
  namespace: portainer-local
spec:
  selector:
    matchLabels:
      run: portainer-local
  template:
    metadata:
      labels:
        run: portainer-local
    spec:
      serviceAccountName: portainer-local-sa-clusteradmin
      containers:
      - name: portainer-local
        image: portainer/base
        # imagePullPolicy: "Never"
        command: ["/app/portainer-local"]
        args: ["--no-analytics",]
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 8000
          hostPort: 8000
        volumeMounts:
        - mountPath: /app
          name: portainer-local-dist
      volumes:
      - name: portainer-local-dist
        hostPath:
          path: /portainer/app
          type: Directory
