apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-ns
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
          name: http