user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  # log_format custom '$remote_addr - $remote_user [$time_local] "$request" '
  #                   '$status $body_bytes_sent "$http_referer" '
  #                   '"$http_user_agent" "$http_x_forwarded_for" "$request_body"';

  log_format custom escape=json '[$time_local] $remote_addr '
  '"$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for" '
  '"$request" '
  '$status $body_bytes_sent '
  '$request_body';

  access_log /var/log/nginx/access.log custom;

  sendfile on;
  keepalive_timeout 65;

  map $request_uri $loggable {
    ~(/api/.*/volumes) 1;
    default 0;
  }

  # Server block for port 9000
  server {
    listen 9000 default_server;
    listen [::]:9000 default_server;

    location / {
      proxy_pass http://192.168.1.20:9000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Log request body
      access_log /var/log/nginx/access.log custom if=$loggable;

      # This is optional, you may need it for larger payloads
      client_max_body_size 10m;
    }
  }

  # Server block for port 8000
  server {
    listen 8000 default_server;
    listen [::]:8000 default_server;

    location / {
      proxy_pass http://192.168.1.20:8000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Log request body
      access_log /var/log/nginx/access.log custom;

      # This is optional, you may need it for larger payloads
      client_max_body_size 10m;
    }
  }
}
